#!/bin/lua.lua
-- Generated by tools/build_installers.py; do not edit.
package.loaded["gtnh_bees.component_call"]=nil
package.preload["gtnh_bees.component_call"]=function(...)
local M = {}

local function callable(value)
  if type(value) == "function" then return true end
  local kind = type(value)
  if kind ~= "table" and kind ~= "userdata" then return false end
  local ok, mt = pcall(getmetatable, value)
  return ok and type(mt) == "table" and type(mt.__call) == "function"
end

function M.exists(proxy, method)
  if not proxy or type(method) ~= "string" or method == "" then return false end
  local ok, member = pcall(function() return proxy[method] end)
  return ok and member ~= nil and callable(member)
end

function M.invoke(component, proxy, address, method, ...)
  if type(method) ~= "string" or method == "" then return nil, "component method name is required" end
  if component and callable(component.invoke) then
    local ok, a, b, c, d = pcall(component.invoke, address, method, ...)
    if not ok then return nil, tostring(a) end
    return true, a, b, c, d
  end
  local ok_member, member = pcall(function() return proxy and proxy[method] end)
  if not ok_member or not callable(member) then return nil, "component method '" .. method .. "' is unavailable" end
  local ok, a, b, c, d = pcall(member, ...)
  if not ok then return nil, tostring(a) end
  return true, a, b, c, d
end

M.callable = callable
return M
end
package.loaded["gtnh_bees.transaction"]=nil
package.preload["gtnh_bees.transaction"]=function(...)
local Transaction={}
local unpack_values=table.unpack or unpack
local function join(a,b)return(a:gsub("/$","")).."/"..(b:gsub("^/",""))end
local MAX_PATH_COMPONENTS=64
local function observe_exists(fs,path)
  local called,exists=pcall(fs.exists,path)
  if not called then return nil,"cannot inspect path "..path..": "..tostring(exists)end
  if type(exists)~="boolean"then return nil,"cannot inspect path "..path..": exists did not return a boolean"end
  return exists
end
local function observe_directory(fs,path)
  local exists,exists_err=observe_exists(fs,path)
  if exists==nil then return nil,exists_err end
  if not exists then return false end
  if type(fs.isDirectory)~="function"then return nil,"filesystem cannot inspect directory type for "..path end
  local directory_called,is_directory=pcall(fs.isDirectory,path)
  if not directory_called then return nil,"cannot inspect directory "..path..": "..tostring(is_directory)end
  if type(is_directory)~="boolean"then return nil,"cannot inspect directory "..path..": isDirectory did not return a boolean"end
  if not is_directory then return nil,"path exists but is not a directory: "..path end
  return true
end
local function ensure_directory(fs,path)
  local exists,inspect_err=observe_directory(fs,path)
  if exists==nil then return nil,inspect_err end
  if exists then return true end
  local called,made,make_err=pcall(fs.makeDirectory,path)
  if not called then return nil,"makeDirectory failed for "..path..": "..tostring(made)end
  local observed,observe_err=observe_directory(fs,path)
  if observed then return true end
  if observed==nil then return nil,observe_err end
  if made then return nil,"makeDirectory reported success but directory was not observed: "..path end
  return nil,"makeDirectory failed for "..path..": "..tostring(make_err or"no error detail")
end
local function require_fresh_path(fs,path)
  local exists,inspect_err=observe_exists(fs,path)
  if exists==nil then return nil,inspect_err end
  if exists then return nil,"transaction root already exists: "..path end
  return true
end
local function create_fresh_directory(fs,path)
  local fresh,fresh_err=require_fresh_path(fs,path)
  if not fresh then return nil,fresh_err end
  local called,made,make_err=pcall(fs.makeDirectory,path)
  if not called then return nil,"makeDirectory failed for fresh transaction root "..path..": "..tostring(made)end
  if not made then
    local exists,inspect_err=observe_exists(fs,path)
    if exists==nil then return nil,inspect_err end
    if exists then return nil,"transaction root appeared while being created: "..path end
    return nil,"makeDirectory failed for fresh transaction root "..path..": "..tostring(make_err or"no error detail")
  end
  local observed,observe_err=observe_directory(fs,path)
  if observed then return true end
  if observed==nil then return nil,observe_err end
  return nil,"fresh transaction root was not observed after creation: "..path
end
local function relative_components(path)
  if type(path)~="string"or path==""or path:sub(1,1)=="/"or path:sub(-1)=="/"or path:find("//",1,true)then return nil,"path is not a normalized relative file path"end
  local components={}
  for component in path:gmatch("[^/]+")do
    if component=="."or component==".."then return nil,"path traversal is not allowed"end
    components[#components+1]=component
    if #components>MAX_PATH_COMPONENTS then return nil,"path exceeds component limit"end
  end
  if #components==0 then return nil,"path has no components"end
  return components
end
local function ensure_relative_parent(fs,root,relative)
  local components,component_err=relative_components(relative)
  if not components then return nil,component_err end
  local current=root
  for index=1,#components-1 do
    current=join(current,components[index])
    local made,make_err=ensure_directory(fs,current)
    if not made then return nil,make_err end
  end
  return true
end
local function relative_to_root(root,path)
  local normalized=root:gsub("/+$","")
  if normalized==""then normalized="/"end
  if normalized=="/"then
    if path:sub(1,1)~="/"then return nil,"path is not rooted at "..normalized end
    return path:sub(2)
  end
  local prefix=normalized.."/"
  if path:sub(1,#prefix)~=prefix then return nil,"path is not rooted at "..normalized end
  return path:sub(#prefix+1)
end
local function checked_remove(fs,path)
  if not fs.exists(path)then return true end
  local ok,err=fs.remove(path);if ok==false or ok==nil then return nil,err or"remove failed"end return true
end
local function journal_temp(path)return path..".tmp"end
local function file_call(handle,method,...)
  local arguments={...}
  return pcall(function()return handle[method](handle,unpack_values(arguments))end)
end
local function write_journal(fs,path,journal)
  local temporary=journal_temp(path)
  if fs.exists(temporary)then return nil,"temporary journal already exists at "..temporary,temporary end
  local handle,err=fs.open(temporary,"w");if not handle then return nil,"cannot create temporary journal "..temporary..": "..tostring(err),temporary end
  local ok,write_err=true
  local called,written,detail=file_call(handle,"write",journal.phase.."\n")
  if not called then ok,write_err=nil,"journal write failed: "..tostring(written)
  elseif not written then ok,write_err=nil,"journal write failed: "..tostring(detail)end
  if ok then
    for _,entry in ipairs(journal.entries)do
      called,written,detail=file_call(handle,"write",table.concat({entry.destination,entry.staged,entry.backup,entry.had_old and"1"or"0",entry.backup_owned and"1"or"0"},"\t"),"\n")
      if not called then ok,write_err=nil,"journal write failed: "..tostring(written);break end
      if not written then ok,write_err=nil,"journal write failed: "..tostring(detail);break end
    end
  end
  if ok then
    if type(handle.flush)~="function"then ok,write_err=nil,"journal handle has no explicit flush"
    else
      local flush_called,flushed,flush_err=file_call(handle,"flush")
      if not flush_called then ok,write_err=nil,"journal flush failed: "..tostring(flushed)
      elseif not flushed then ok,write_err=nil,"journal flush failed: "..tostring(flush_err)end
    end
  end
  local close_called,closed,close_err=file_call(handle,"close")
  if not close_called then ok,write_err=nil,(write_err and(write_err.."; ")or"").."journal close failed: "..tostring(closed)
  elseif closed==false or(closed==nil and close_err~=nil)then ok,write_err=nil,(write_err and(write_err.."; ")or"").."journal close failed: "..tostring(close_err)end
  if not ok then return nil,write_err or"temporary journal write failed",temporary end
  local rename_called,renamed,rename_err=pcall(fs.rename,temporary,path)
  if not rename_called then return nil,"cannot atomically replace journal "..path.." from "..temporary..": "..tostring(renamed),temporary end
  if not renamed then return nil,"cannot atomically replace journal "..path.." from "..temporary..": "..tostring(rename_err),temporary end
  return true,nil,temporary
end
local function read_journal(fs,path)
  local handle=fs.open(path,"r");if not handle then return nil,"cannot open install recovery journal"end
  local phase=handle:read("*l");local entries={}
  for line in handle:lines()do
    local destination,staged,backup,old,owned=line:match("^([^\t]+)\t([^\t]+)\t([^\t]+)\t([01])\t([01])$")
    if not destination or(owned=="1"and old~="1")then handle:close();return nil,"install journal is malformed"end
    entries[#entries+1]={destination=destination,staged=staged,backup=backup,had_old=old=="1",backup_owned=owned=="1"}
  end
  handle:close();if phase~="installing"and phase~="committed"then return nil,"install journal phase is malformed"end
  if phase=="committed"then for _,entry in ipairs(entries)do if entry.had_old and not entry.backup_owned then return nil,"install journal is malformed"end end end
  return {phase=phase,entries=entries}
end
local function rollback(fs,journal)
  local errors={}
  for index=#journal.entries,1,-1 do
    local entry=journal.entries[index]
    local backup_exists=fs.exists(entry.backup)
    if backup_exists and not entry.backup_owned then
      errors[#errors+1]=entry.destination.." (unowned backup retained at "..entry.backup..")"
    elseif entry.had_old and entry.backup_owned then
      if fs.exists(entry.backup)then
        if fs.exists(entry.destination)then local removed,remove_err=checked_remove(fs,entry.destination);if not removed then errors[#errors+1]=entry.destination.." (cannot remove new file: "..tostring(remove_err)..")" end end
        if not fs.exists(entry.destination)then local ok,err=fs.rename(entry.backup,entry.destination);if not ok then errors[#errors+1]=entry.destination.." (backup remains "..entry.backup..": "..tostring(err)..")"end end
      elseif not fs.exists(entry.destination)then errors[#errors+1]=entry.destination.." (destination and backup are both absent)"end
    elseif entry.had_old then
      if not fs.exists(entry.destination)then errors[#errors+1]=entry.destination.." (destination is absent and no transaction-owned backup was recorded)"end
    elseif fs.exists(entry.destination)then local ok,err=checked_remove(fs,entry.destination);if not ok then errors[#errors+1]=entry.destination.." (new file removal failed: "..tostring(err)..")"end end
  end
  if #errors>0 then return nil,"rollback incomplete; unresolved paths: "..table.concat(errors,"; ")end
  return true
end
Transaction.rollback=rollback
local function remove_temporary(fs,temporary,prefix)
  local removed,remove_err=checked_remove(fs,temporary)
  if not removed then return nil,prefix..": "..tostring(remove_err).."; path "..temporary end
  return true
end
function Transaction.recover(fs,journal_path)
  local temporary=journal_temp(journal_path)
  if not fs.exists(journal_path)then
    if fs.exists(temporary)then return remove_temporary(fs,temporary,"unpublished temporary journal could not be removed")end
    return true
  end
  local journal,err=read_journal(fs,journal_path)
  if not journal then
    local retained=fs.exists(temporary)and("; temporary journal retained at "..temporary)or""
    return nil,err.."; recovery artifact retained at "..journal_path..retained
  end
  if journal.phase=="committed"then
    for _,entry in ipairs(journal.entries)do
      local backup_exists,inspect_err=observe_exists(fs,entry.backup)
      if backup_exists==nil then return nil,"cannot inspect committed backup path "..entry.backup..": "..tostring(inspect_err).."; journal retained at "..journal_path end
      if backup_exists and not entry.backup_owned then return nil,"committed transaction has unowned backup retained at "..entry.backup.."; journal retained at "..journal_path end
    end
  end
  if journal.phase=="installing"then
    local ok,rollback_err=rollback(fs,journal)
    if not ok then
      local retained=fs.exists(temporary)and("; temporary journal retained at "..temporary)or""
      return nil,rollback_err.."; journal retained at "..journal_path..retained
    end
  end
  local removed,remove_err=checked_remove(fs,journal_path)
  if not removed then return nil,"transaction resolved but journal could not be removed: "..tostring(remove_err).."; path "..journal_path end
  return remove_temporary(fs,temporary,"transaction resolved but temporary journal could not be removed")
end
local function failed_commit(fs,journal_path,temporary,original)
  local journal,journal_err=read_journal(fs,journal_path)
  if not journal then
    local temp_detail=fs.exists(temporary)and("; temporary journal retained at "..temporary)or""
    return nil,original.."; cannot read durable rollback authority: "..tostring(journal_err).."; recovery artifacts retained at "..journal_path..temp_detail
  end
  if journal.phase~="installing"then return nil,original.."; durable journal is not in installing phase; recovery artifacts retained at "..journal_path end
  local rolled,rollback_err=rollback(fs,journal)
  if not rolled then
    local temp_detail=fs.exists(temporary)and("; temporary journal retained at "..temporary)or""
    return nil,original.."; "..rollback_err.."; recovery journal and backups retained at "..journal_path..temp_detail
  end
  local removed,remove_err=checked_remove(fs,journal_path)
  if not removed then return nil,original.."; prior file set restored but recovery journal remains at "..journal_path..": "..tostring(remove_err)end
  removed,remove_err=checked_remove(fs,temporary)
  if not removed then return nil,original.."; prior file set restored but temporary journal remains at "..temporary..": "..tostring(remove_err)end
  return nil,original.."; prior file set was fully restored"
end
function Transaction.install(options)
  local fs,fetch=assert(options.fs),assert(options.fetch);local root=assert(options.root)
  local journal_path=options.journal or join(root,".gtnh-bees-install.journal")
  local temporary=journal_temp(journal_path)
  local root_directory,root_err=observe_directory(fs,root)
  if not root_directory then return nil,"cannot use install root: "..tostring(root_err or("directory does not exist: "..root))end
  local recovered,recover_err=Transaction.recover(fs,journal_path);if not recovered then return nil,recover_err end
  local token=tostring((options.now or os.time)());local stage_root=join(root,".gtnh-bees-stage-"..token);local backup_root=join(root,".gtnh-bees-backup-"..token)
  local fresh,fresh_err=require_fresh_path(fs,stage_root);if not fresh then return nil,"cannot create stage: "..tostring(fresh_err)end
  fresh,fresh_err=require_fresh_path(fs,backup_root);if not fresh then return nil,"cannot create backup: "..tostring(fresh_err)end
  local made,make_err=create_fresh_directory(fs,stage_root);if not made then return nil,"cannot create stage: "..tostring(make_err)end
  made,make_err=create_fresh_directory(fs,backup_root);if not made then return nil,"cannot create backup: "..tostring(make_err).."; staging retained at "..stage_root end
  local entries={}
  for _,item in ipairs(options.manifest)do
    local staged,destination,backup=join(stage_root,item.path),join(root,item.path),join(backup_root,item.path)
    local components,path_err=relative_components(item.path)
    if not components then return nil,"invalid transaction path "..tostring(item.path)..": "..tostring(path_err)end
    entries[#entries+1]={destination=destination,staged=staged,backup=backup,item=item,backup_owned=false}
  end
  for _,entry in ipairs(entries)do
    local ok,err=ensure_relative_parent(fs,stage_root,entry.item.path)
    if not ok then return nil,"cannot create staging parent for "..entry.item.path..": "..tostring(err).."; staging retained at "..stage_root end
  end
  for _,entry in ipairs(entries)do
    local ok,err=ensure_relative_parent(fs,backup_root,entry.item.path)
    if not ok then return nil,"cannot create backup parent for "..entry.item.path..": "..tostring(err).."; staging retained at "..stage_root end
  end
  local journal_relative,journal_root_err=relative_to_root(root,journal_path)
  if not journal_relative then return nil,"cannot prepare install journal path: "..tostring(journal_root_err).."; staging retained at "..stage_root end
  made,make_err=ensure_relative_parent(fs,root,journal_relative)
  if not made then return nil,"cannot create journal parent: "..tostring(make_err).."; staging retained at "..stage_root end
  for _,entry in ipairs(entries)do
    local ok,err=ensure_relative_parent(fs,root,entry.item.path)
    if not ok then return nil,"cannot create destination parent for "..entry.item.path..": "..tostring(err).."; staging retained at "..stage_root end
  end
  for _,entry in ipairs(entries)do
    local item=entry.item
    local ok,err=fetch(item.url,entry.staged,item)
    if not ok then return nil,"download failed for "..item.path..": "..tostring(err).."; staging retained at "..stage_root end
    local destination_exists,inspect_err=observe_exists(fs,entry.destination)
    if destination_exists==nil then return nil,"cannot inspect destination for "..item.path..": "..tostring(inspect_err).."; staging retained at "..stage_root end
    entry.had_old=destination_exists
    entry.item=nil
  end
  local journal={phase="installing",entries=entries};local recorded,journal_err=write_journal(fs,journal_path,journal)
  if not recorded then return nil,"cannot record install transaction: "..tostring(journal_err).."; staging retained at "..stage_root.."; temporary journal path "..temporary end
  for _,entry in ipairs(entries)do
    if entry.had_old then
      local backup_exists,inspect_err=observe_exists(fs,entry.backup)
      if backup_exists==nil then return failed_commit(fs,journal_path,temporary,"cannot inspect backup path "..entry.backup..": "..tostring(inspect_err))end
      if backup_exists then return failed_commit(fs,journal_path,temporary,"refusing unowned backup already present at "..entry.backup)end
      entry.backup_owned=true
      local owned,ownership_err=write_journal(fs,journal_path,journal)
      if not owned then return failed_commit(fs,journal_path,temporary,"cannot record durable backup ownership for "..entry.backup..": "..tostring(ownership_err))end
      local ok,err=fs.rename(entry.destination,entry.backup)
      if not ok then return failed_commit(fs,journal_path,temporary,"cannot back up "..entry.destination..": "..tostring(err))end
    end
    local ok,err=fs.rename(entry.staged,entry.destination);if not ok then return failed_commit(fs,journal_path,temporary,"cannot install "..entry.destination..": "..tostring(err))end
  end
  journal.phase="committed";local committed,commit_err=write_journal(fs,journal_path,journal)
  if not committed then return failed_commit(fs,journal_path,temporary,"cannot commit install journal: "..tostring(commit_err))end
  local removed,remove_err=checked_remove(fs,journal_path);if not removed then return nil,"new release installed but committed journal remains at "..journal_path..": "..tostring(remove_err)end
  checked_remove(fs,stage_root)
  return true,backup_root
end
return Transaction
end
package.loaded["gtnh_bees.install_manifest"]=nil
package.preload["gtnh_bees.install_manifest"]=function(...)
local M={}
local pinned={
  ["bin/bees"]={size=158,sha256="d3c9a3b47497f3f560ca14c164d4a3beb723306cd3a9147ea50a10862ae1a62b"},
  ["bin/bees-robot"]={size=164,sha256="01262337e521434542e3d8a9d56b774366aa85008e370dc7cb058a4fc5bca8c6"},
  ["lib/gtnh_bees/application.lua"]={size=4016,sha256="486b56d26781f87dafae28bbcb017540084b12c837714c153cec91545c072219"},
  ["lib/gtnh_bees/bounded.lua"]={size=1117,sha256="a2a8369a94906e01cf32b4bda8b502115d7d13741d532fff545208f8c268fb9c"},
  ["lib/gtnh_bees/catalog.lua"]={size=11997,sha256="0c4ba7aac86d72646e34d4969b66d9ef797e6b585024eee3685734aace0494b7"},
  ["lib/gtnh_bees/command.lua"]={size=4040,sha256="991370243b5e8b2ee39a3d8572272d0301fd4dd84fb25ac743de5aca239b1b98"},
  ["lib/gtnh_bees/component_call.lua"]={size=1258,sha256="a5e5be25631e3e96791d7042646dde8488a5d16f8cc49608d813f38077599f09"},
  ["lib/gtnh_bees/config.lua"]={size=14464,sha256="159182ddb55090046470c26a0b17fad15359c94e25f55d40b137edb2496b13a5"},
  ["lib/gtnh_bees/foundation.lua"]={size=7360,sha256="8e1ca2fd251ab6bfb98a100d6edeaa30c89a0ac011339b2da2e81191b50a3904"},
  ["lib/gtnh_bees/hardware.lua"]={size=31291,sha256="9544d232526e8ad2603bf5ea95d5a9d460c60e72d34471eb332537c41e028ede"},
  ["lib/gtnh_bees/identity.lua"]={size=2820,sha256="7c2d571640b7025ba6c40348f11fd985f5a37db6a7d814dd01777b75b13a0613"},
  ["lib/gtnh_bees/inventory.lua"]={size=7623,sha256="094b604c5fc91ce2efa3045b360349ee06b04ede476a48c6e042e8966a205aeb"},
  ["lib/gtnh_bees/main.lua"]={size=2504,sha256="e4809b34cba2f19ba68294515846b0f2e9e6b373c6427276dc5d7e06666c32a5"},
  ["lib/gtnh_bees/menu.lua"]={size=4142,sha256="8f4019c8be61ccb1a6368f5ccbc64a7af9f4a0e40affc14bd9397cee190a2422"},
  ["lib/gtnh_bees/official_driver.lua"]={size=28474,sha256="06c7583c9877ef1e7723ae6ba548f3374a2cd8d1bcfeed64f3403826dc17503d"},
  ["lib/gtnh_bees/operations.lua"]={size=31982,sha256="49131b369ec4297cdc890a3a0f03a8bbddd8bce7e2f070626d7ec7cce00ba9be"},
  ["lib/gtnh_bees/planner.lua"]={size=7789,sha256="4d043d5fa9a6a89a00533ff4e460c8eb60143f64db1dbaae97aa0562d43c2e17"},
  ["lib/gtnh_bees/robot_main.lua"]={size=4182,sha256="115a473753f63edd73914a55b87eae3cd5163011956e28f8c63a63c94d57c7c6"},
  ["lib/gtnh_bees/robot_service.lua"]={size=27728,sha256="6691f7238b41a78f75dba9f7dfadec0b47e9f02cf40461d85ed11c4be911c943"},
  ["lib/gtnh_bees/transaction.lua"]={size=18018,sha256="18d1eaab684bec8c5f0e4b0466b6c1404f228ea98160b04e6c635887aa1528d4"},
  ["lib/gtnh_bees/util.lua"]={size=2120,sha256="1ca3a14769012fed5e62235828406aaafaab3586095e666ee5724a7ffbd47836"}
}
local shared={"util.lua","identity.lua","bounded.lua","component_call.lua","inventory.lua","foundation.lua"}
local computer={"catalog.lua","planner.lua","command.lua","menu.lua","config.lua","transaction.lua","hardware.lua","operations.lua","application.lua","official_driver.lua","main.lua"}
local robot={"robot_service.lua","robot_main.lua"}
local function entry(base,source,destination)
  local pin=assert(pinned[source],"release manifest pin missing for "..source)
  return {url=base..source,path=destination,size=pin.size,sha256=pin.sha256}
end
local function build(base,executable,modules)
  local source="bin/"..executable;local manifest={entry(base,source,"usr/bin/"..executable)}
  for _,name in ipairs(modules)do source="lib/gtnh_bees/"..name;manifest[#manifest+1]=entry(base,source,"usr/lib/gtnh_bees/"..name)end
  return manifest
end
function M.computer(base)local modules={}for _,name in ipairs(shared)do modules[#modules+1]=name end for _,name in ipairs(computer)do modules[#modules+1]=name end return build(base,"bees",modules)end
function M.robot(base)local modules={}for _,name in ipairs(shared)do modules[#modules+1]=name end for _,name in ipairs(robot)do modules[#modules+1]=name end return build(base,"bees-robot",modules)end
return M
end
package.loaded["gtnh_bees.installer"]=nil
package.preload["gtnh_bees.installer"]=function(...)
local Calls=require("gtnh_bees.component_call")
local Transaction=require("gtnh_bees.transaction")
local Manifest=require("gtnh_bees.install_manifest")
local M={}
local function fs_wrapper(filesystem)return {exists=filesystem.exists,isDirectory=filesystem.isDirectory,rename=filesystem.rename,remove=filesystem.remove,makeDirectory=filesystem.makeDirectory,open=io.open}end
local function call(object,method,...)
  local member=object and object[method]
  if not Calls.callable(member)then return nil,"request handle lacks '"..method.."'"end
  local ok,a,b,c=pcall(member,...);if not ok then return nil,tostring(a)end return a,b,c
end
local function hex(value)return(tostring(value):gsub(".",function(c)return string.format("%02x",string.byte(c))end))end
local function close(handle)if handle then pcall(function()handle.close()end)end end
local function valid_count(value)return type(value)=="number"and value>=0 and value<math.huge and value%1==0 end
local function checked_file_close(handle,label)
  local called,closed,close_err=pcall(function()return handle:close()end)
  if not called then return nil,label.." close failed: "..tostring(closed)end
  if closed==false or(closed==nil and close_err~=nil)then return nil,label.." close failed: "..tostring(close_err)end
  return true
end
local function verify_staged(runtime,destination,item,limits)
  local opened,handle,open_err=pcall(runtime.open,destination,"rb")
  if not opened then return nil,"cannot reopen staged file "..destination..": "..tostring(handle)end
  if not handle then return nil,"cannot reopen staged file "..destination..": "..tostring(open_err)end
  local inspected,member=pcall(function()return handle.read end)
  if not inspected or not Calls.callable(member)then
    local _,close_err=checked_file_close(handle,"staged verification")
    local read_err=not inspected and("staged file read failed for "..destination..": "..tostring(member))or"staged SHA-256 verification handle lacks read"
    return nil,read_err..(close_err and"; "..close_err or"")
  end
  local chunk_size=limits.verify_chunk or 8192
  if not valid_count(chunk_size)or chunk_size<1 then
    local _,close_err=checked_file_close(handle,"staged verification")
    return nil,"staged verification chunk budget is invalid"..(close_err and"; "..close_err or"")
  end
  local read_budget=limits.verify_reads or(math.ceil(item.size/chunk_size)+16)
  if not valid_count(read_budget)or read_budget<1 then
    local _,close_err=checked_file_close(handle,"staged verification")
    return nil,"staged verification read budget is invalid"..(close_err and"; "..close_err or"")
  end
  local chunks,total,reads={},0,0
  local failure
  while not failure do
    reads=reads+1
    if reads>read_budget then failure="staged verification read budget exceeded for "..destination;break end
    local amount=math.min(chunk_size,item.size-total+1)
    local called,chunk,read_err=pcall(function()return handle:read(amount)end)
    if not called then failure="staged file read failed for "..destination..": "..tostring(chunk)
    elseif chunk==nil then
      if read_err~=nil then failure="staged file read failed for "..destination..": "..tostring(read_err)else break end
    elseif type(chunk)~="string"then failure="staged file read returned malformed data for "..destination
    elseif #chunk>0 then
      total=total+#chunk
      if total>item.size then failure="staged file exceeds pinned size "..item.size.." at "..destination
      else chunks[#chunks+1]=chunk end
    end
  end
  local closed,close_err=checked_file_close(handle,"staged verification")
  if not closed then failure=failure and(failure.."; "..close_err)or close_err end
  if failure then return nil,failure end
  if total~=item.size then return nil,"staged file is short at "..destination..": read "..total.." bytes, pinned size is "..item.size end
  local called,digest,digest_err=pcall(runtime.data.sha256,table.concat(chunks))
  if not called then return nil,"staged SHA-256 failed: "..tostring(digest)end
  if type(digest)~="string"then return nil,"staged SHA-256 failed: "..tostring(digest_err)end
  if hex(digest)~=item.sha256:lower()then return nil,"staged file SHA-256 does not match pinned manifest at "..destination end
  return true
end
local function fetcher(runtime,limits)
  limits=limits or {};local clock=assert(runtime.computer.uptime);local started=clock()
  local connect_limit=limits.connect or 10;local read_limit=limits.read or 10;local file_limit=limits.file or 60;local overall_limit=limits.overall or 300
  return function(url,destination,item)
    if type(item)~="table"or not valid_count(item.size)or type(item.sha256)~="string"then return nil,"manifest entry lacks pinned size/digest"end
    local file_started=clock();if file_started-started>overall_limit then return nil,"installer overall deadline reached before request"end
    local request,request_err=runtime.internet.request(url)
    if not request then return nil,request_err end
    while true do
      local connected,connect_err=call(request,"finishConnect")
      if connected==true then break end
      if connect_err then close(request);return nil,"connection failed: "..tostring(connect_err)end
      local now=clock();if now-file_started>connect_limit or now-started>overall_limit then close(request);return nil,"connection deadline reached"end
      runtime.computer.pullSignal(0.05)
    end
    local code,message=call(request,"response")
    if type(code)~="number"or code<200 or code>=300 then close(request);return nil,"HTTPS response was "..tostring(code).." "..tostring(message)end
    local handle,open_err=runtime.open(destination,"wb");if not handle then close(request);return nil,open_err end
    local total,last=0,clock()
    local function fail(reason)close(request);if handle then pcall(function()handle:close()end)end;return nil,reason end
    while true do
      local chunk,read_err=call(request,"read",8192)
      local now=clock()
      if chunk==nil then if read_err then return fail("read failed: "..tostring(read_err))end break end
      if type(chunk)~="string"then return fail("read returned a malformed chunk")end
      if #chunk>0 then
        total=total+#chunk;if total>item.size then return fail("download exceeds pinned size")end
        local called,written,write_err=pcall(function()return handle:write(chunk)end)
        if not called then return fail("write failed: "..tostring(written))end
        if not written then return fail("write failed: "..tostring(write_err))end
        last=now
      elseif now-last>read_limit then return fail("read deadline reached")end
      if now-file_started>file_limit then return fail("file deadline reached")end
      if now-started>overall_limit then return fail("installer overall deadline reached")end
      if #chunk==0 then runtime.computer.pullSignal(0.05)end
    end
    close(request)
    if total~=item.size then return fail("download size "..total.." does not match pinned size "..item.size)end
    if type(handle.flush)~="function"then return fail("download handle has no explicit flush")end
    local called,flushed,flush_err=pcall(function()return handle:flush()end)
    if not called then return fail("download flush failed: "..tostring(flushed))end
    if not flushed then return fail("download flush failed: "..tostring(flush_err))end
    local closed,close_err=checked_file_close(handle,"download");handle=nil
    if not closed then return nil,close_err end
    return verify_staged(runtime,destination,item,limits)
  end
end
M.fetcher=fetcher
function M.run(kind,argv,runtime)
  argv=argv or {}
  local base
  for _,arg in ipairs(argv)do
    local value=arg:match("^%-%-base%-url=(.+)$")or arg:match("^(https://.+)$")
    if value then if base then return nil,"installer base URL was supplied more than once"end;base=value
    elseif arg=="--help"or arg=="-h"then print("Usage: install-"..kind..".lua https://approved-host/path/");return true
    else return nil,"unknown installer option '"..arg.."'"end
  end
  if not base or not base:match("^https://")then return nil,"an HTTPS base URL is required"end;if base:sub(-1)~="/"then base=base.."/"end
  if not runtime then
    local component=require("component")
    local function primary(name)local ok,value=pcall(function()return component[name]end);if ok then return value end end
    runtime={filesystem=require("filesystem"),internet=primary("internet"),data=primary("data"),computer=require("computer"),open=io.open}
  end
  runtime.open=runtime.open or io.open
  if not runtime.internet then return nil,"an internet card is required"end
  if not runtime.data or not Calls.callable(runtime.data.sha256)then return nil,"a tier-2-or-better data card providing SHA-256 is required for pinned release validation"end
  local manifest=kind=="robot"and Manifest.robot(base)or Manifest.computer(base)
  local ok,backup_or_err=Transaction.install({fs=fs_wrapper(runtime.filesystem),fetch=fetcher(runtime,runtime.deadlines),root="/",manifest=manifest})
  if not ok then return nil,backup_or_err end
  print("Installed a complete verified "..kind.." file set. Previous files remain in "..backup_or_err);return true
end
return M
end
local ok,err=require("gtnh_bees.installer").run("computer",{...})
if not ok then io.stderr:write("Install failed: ",tostring(err),"\n");os.exit(1)end
