package.path = "./lib/?.lua;./tests/?.lua;./?.lua;" .. package.path
local H = require("tests.harness")
require("tests.test_core")
require("tests.test_ui")
require("tests.test_safety")
require("tests.test_runtime")
require("tests.test_genetics")
require("tests.test_installer")
require("tests.test_foundation")
require("tests.test_platform")
require("tests.test_planning")
require("tests.test_storage")
require("tests.test_config")
require("tests.test_lineage")
require("tests.test_recovery")
require("tests.test_validation")
require("tests.test_transaction")
require("tests.test_transaction_recovery")
require("tests.test_foundation_replay")
require("tests.test_discovery")
require("tests.test_ui_safety")
local ok = H.run()
if not ok then os.exit(1) end
