local H = require("tests.harness")
local Command = require("gtnh_bees.command")
local Menu = require("gtnh_bees.menu")
local Main = require("gtnh_bees.main")

H.test("CLI defaults to menu without arguments", function() H.equal(assert(Command.parse({})),{name="menu"}) end)
H.test("breed defaults and quoted species stay hardware independent", function()
  H.equal(assert(Command.parse({"breed","Steadfast Worker"})),{name="breed",species="Steadfast Worker",imprint="all",pause=false})
end)
H.test("breed validates imprint mode", function() local value,err=Command.parse({"breed","A","--imprint=maybe"}); H.falsy(value); H.contains(err,"invalid imprint") end)
H.test("conversion defaults to one", function() H.equal(assert(Command.parse({"convert","A"})),{name="convert",species="A",count=1,all=false}) end)
H.test("conversion rejects count with all", function() local value,err=Command.parse({"convert","A","--count=2","--all"}); H.falsy(value); H.contains(err,"not both") end)
H.test("conversion rejects zero and fractions", function()
  local a=Command.parse({"convert","A","--count=0"}); local b=Command.parse({"convert","A","--count=1.5"}); H.falsy(a); H.falsy(b)
end)
H.test("help does not construct hardware", function()
  local factory_calls, output=0,{}
  local ok=Main.run({"help","breed"},{factory=function() factory_calls=factory_calls+1; error("must not run") end,output=function(line) output[#output+1]=line end})
  H.truthy(ok); H.equal(factory_calls,0); H.contains(output[1],"bees breed")
end)
H.test("argument validation does not construct hardware", function()
  local factory_calls=0; local ok=Main.run({"convert","A","--all","--count=2"},{factory=function() factory_calls=factory_calls+1 end,output=function() end})
  H.falsy(ok); H.equal(factory_calls,0)
end)
H.test("TUI complete maps to the CLI representation", function()
  H.truthy(Command.equal(assert(Menu.command_for("complete")),assert(Command.parse({"complete"}))))
end)
H.test("TUI breed maps to the CLI representation", function()
  local tui=assert(Menu.command_for("breed",{species="Forest Sage",imprint="target",pause=true}))
  local cli=assert(Command.parse({"breed","Forest Sage","--imprint=target","--pause"})); H.truthy(Command.equal(tui,cli))
end)
H.test("TUI conversion maps to the CLI representation", function()
  local tui=assert(Menu.command_for("convert",{species="A",all=true})); local cli=assert(Command.parse({"convert","A","--all"})); H.truthy(Command.equal(tui,cli))
end)
H.test("TUI imprint-all maps to the CLI representation", function()
  local tui=assert(Menu.command_for("imprint",{species=""})); local cli=assert(Command.parse({"imprint"})); H.truthy(Command.equal(tui,cli))
end)
H.test("robot help is hardware independent", function()
  local RobotMain=require("gtnh_bees.robot_main"); local lines={}; local ok=RobotMain.run({"--help"},{output=function(v) lines[#lines+1]=v end})
  H.truthy(ok); H.contains(lines[1],"bees-robot")
end)

H.test("full TUI rejects a malformed nonblank conversion count",function()
  local old_read,old_write,old_print=io.read,io.write,print
  local answers={"A","abc",""};local events={2,2,3,4};local executed=0
  io.read=function()return table.remove(answers,1)end;io.write=function()end;print=function()end
  local runtime={term={clear=function()end},keyboard={keys={up=1,down=2,enter=3,q=4,esc=5,back=6}},event={pull=function()return"key_down",nil,nil,table.remove(events,1)end}}
  local ok,err=pcall(function()Menu.run(function()executed=executed+1;return true end,runtime)end)
  io.read,io.write,print=old_read,old_write,old_print
  H.truthy(ok,err);H.equal(executed,0)
end)
