#!/usr/bin/env python3
"""Generate self-contained OpenOS installer launchers."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES = (
    "component_call",
    "transaction",
    "install_manifest",
    "installer",
)
TARGETS = {
    "computer": ROOT / "install-computer.lua",
    "robot": ROOT / "install-robot.lua",
}


def render(kind: str) -> str:
    chunks = [
        "#!/usr/bin/lua\n",
        "-- Generated by tools/build_installers.py; do not edit.\n",
    ]
    for name in MODULES:
        module = f"gtnh_bees.{name}"
        source = (ROOT / "lib" / "gtnh_bees" / f"{name}.lua").read_text(encoding="utf-8")
        if not source.endswith("\n"):
            source += "\n"
        chunks.extend(
            (
                f'package.loaded["{module}"]=nil\n',
                f'package.preload["{module}"]=function(...)\n',
                source,
                "end\n",
            )
        )
    chunks.extend(
        (
            'local argv={...}\n',
            'if #argv==0 and type(arg)=="table"then for index=1,#arg do argv[#argv+1]=arg[index]end end\n',
            f'local ok,err=require("gtnh_bees.installer").run("{kind}",argv)\n',
            'if not ok then io.stderr:write("Install failed: ",tostring(err),"\\n");os.exit(1)end\n',
        )
    )
    return "".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated launchers are stale")
    args = parser.parse_args()

    stale = []
    for kind, target in TARGETS.items():
        expected = render(kind)
        if args.check:
            if not target.is_file() or target.read_text(encoding="utf-8") != expected:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        print("stale generated installer launcher(s): " + ", ".join(stale), file=sys.stderr)
        print("run: python tools/build_installers.py", file=sys.stderr)
        return 1
    if args.check:
        print(f"generated installer launchers verified: {len(TARGETS)} files")
    else:
        print(f"generated installer launchers updated: {len(TARGETS)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
